trip_name: "New Zealand Adventure 2026"
timezone: "Pacific/Auckland"
people:
  - name: "David"
    slug: "david"
  - name: "Diego"
    slug: "diego"
  - name: "John"
    slug: "john"
  - name: "Clara"
    slug: "clara"
  - name: "Alex"
    slug: "alex"
  - name: "Stephanie"
    slug: "stephanie"
